name: Despliegue automatizado
on:
  push:
    branches:
      - main
jobs:
  despliegue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependencias (Linux)
        run: |
          sudo apt update
          sudo apt install -y openssh-client rsync sshpass

      - name: Desplegar a HwPeru v2
        run: |
          sudo sshpass -p 'nodejs' rsync -r --exclude 'node_modules/' --exclude '.next/' . root@15.235.16.194:/data \
            -e "ssh -p 50005 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          sudo sshpass -p 'nodejs' ssh -o StrictHostKeyChecking=no root@15.235.16.194 -p 50005 \
            "cd /data && npm install -g pnpm && pnpm i && pnpm run build && (pm2 describe consorcio-front > /dev/null && pm2 restart consorcio-front || pm2 start ecosystem.config.js)"
